name = "koperasi-backend"
type = "javascript"
main = "src/worker/index.mjs"
workers_dev = true
compatibility_date = "2026-02-13"
compatibility_flags = ["nodejs_compat"]
account_id = "96f2f075a58d38a4c130161f1e70cc0b"

[vars]
GOOGLE_SPREADSHEET_ID = "11rzIkhogRXuHzUHrvOi3J6xs4s_bO4QplcF5_nHrIMA"

[env.production]
name = "koperasi-web-prod"
compatibility_flags = ["nodejs_compat"]
vars = { GOOGLE_SPREADSHEET_ID = "11rzIkhogRXuHzUHrvOi3J6xs4s_bO4QplcF5_nHrIMA" }

